## Deliverable 2. Create a Customer Travel Destinations Map.

In [38]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [26]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("weather_database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
0,0,Tasiilaq,65.61,-37.64,37.40,100,0,5.82,GL,2020-08-23 23:37:23,fog
1,1,Benguela,-12.58,13.41,67.66,89,29,0.72,AO,2020-08-23 23:38:53,scattered clouds
2,2,Ribeira Grande,38.52,-28.70,73.35,89,3,10.36,PT,2020-08-23 23:33:59,clear sky
3,3,Upernavik,72.79,-56.15,43.25,88,94,0.94,GL,2020-08-23 23:38:53,overcast clouds
4,4,Paamiut,61.99,-49.67,42.55,91,16,6.24,GL,2020-08-23 23:36:24,few clouds

In [29]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 

# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 80

In [30]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
1,1,Benguela,-12.58,13.41,67.66,89,29,0.72,AO,2020-08-23 23:38:53,scattered clouds
2,2,Ribeira Grande,38.52,-28.70,73.35,89,3,10.36,PT,2020-08-23 23:33:59,clear sky
5,5,Sao Joao Da Barra,-21.64,-41.05,64.89,72,3,11.61,BR,2020-08-23 23:36:51,clear sky
7,7,Bambous Virieux,-20.34,57.76,71.60,78,40,16.11,MU,2020-08-23 23:33:48,scattered clouds
8,8,Abu Zabad,12.35,29.25,73.00,75,99,9.31,SD,2020-08-23 23:38:54,light rain
10,10,Tual,-5.67,132.75,79.39,77,33,18.99,ID,2020-08-23 23:34:46,scattered clouds
12,12,Moindou,-21.69,165.68,69.80,88,90,2.24,NC,2020-08-23 23:38:55,overcast clouds
13,13,Santa Maria Da Boa Vista,-8.81,-39.83,78.12,60,30,21.18,BR,2020-08-23 23:38:55,scattered clouds
14,14,Los Llanos De Aridane,28.66,-17.92,73.40,83,9,17.22,ES,2020-08-23 23:38:55,clear sky
18,18,Bengkulu,-3.80,102.27,75.88,85,99,4.27,ID,2020-08-23 23:38:56,overcast clouds

In [31]:
# 4a. Determine if there are any empty rows.
# preferred_cities_df.count()
# preferred_cities_df.iloc[:,2].isnull().sum

In [32]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
# No empty rows
# nan_value = float("NaN")
# clean_df = preferred_cities_df.dropna("", nan_value, inplace=True)

In [33]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""

In [34]:
# Set the parameters to search for a hotel in Paris.
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")


# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError, KeyError):
        print("Hotel not found... skipping.")
       
# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
-----------------------------
Data Retrieval Complete
-----------------------------

In [36]:
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Benguela,AO,67.66,scattered clouds,-12.58,13.41,Hotel Praia Morena
2,Ribeira Grande,PT,73.35,clear sky,38.52,-28.70,Quinta da Meia Eira
5,Sao Joao Da Barra,BR,64.89,clear sky,-21.64,-41.05,Pousada Porto De Canoas
7,Bambous Virieux,MU,71.60,scattered clouds,-20.34,57.76,Casa Tia Villa
8,Abu Zabad,SD,73.00,light rain,12.35,29.25,محي الدين نوري

In [39]:
# 7. Drop the rows where there is no Hotel Name.
clean = hotel_df.replace(r'^\s*$', np.nan, regex=True)
clean_hotel_df = clean.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Benguela,AO,67.66,scattered clouds,-12.58,13.41,Hotel Praia Morena
2,Ribeira Grande,PT,73.35,clear sky,38.52,-28.70,Quinta da Meia Eira
5,Sao Joao Da Barra,BR,64.89,clear sky,-21.64,-41.05,Pousada Porto De Canoas
7,Bambous Virieux,MU,71.60,scattered clouds,-20.34,57.76,Casa Tia Villa
8,Abu Zabad,SD,73.00,light rain,12.35,29.25,محي الدين نوري
...,...,...,...,...,...,...,...
2027,Mahon,ES,71.60,clear sky,39.89,4.27,ARTIEM Capri
2029,Moussoro,TD,78.48,broken clouds,13.64,16.49,Pharmacie alnadja Moussoro
2037,Montes Claros,BR,63.52,scattered clouds,-16.73,-43.86,ibis Montes Claros Shopping
2041,Bruckmuhl,DE,60.01,scattered clouds,47.88,11.92,Gasthof-Hotel Zur schönen Aussicht
2042,Phalaborwa,ZA,64.40,clear sky,-23.94,31.14,Bothabelo B&B

In [41]:
# 8a. Create the output File (CSV)
output_data_file = "vacation_search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [42]:

# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [43]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# 11b. Display the figure
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.4)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))